version: '3'

services:
  html:
    image: nginx:latest
    container_name: html
    ports:
      - "8080:80"
    volumes:
      - ./app-html:/usr/share/nginx/html
    networks:
      - toshiro-net

  node:
    build: ./app-node
    container_name: node
    ports:
      - "3000:3000"
    networks:
      - toshiro-net

  python:
    build: ./app-python
    container_name: python
    ports:
      - "5000:5000"
    networks:
      - toshiro-net

networks:
  toshiro-net:
    driver: bridge
